### PR TITLE
Update strings.xml for Spanish translation

### PR DESCRIPTION
**Pull request by alesnav**

### CODE REVIEW

**Comment by alesnav** [comment]
Some missing strings in Spanish translation... added to be fully translated to Spanish :)

**Comment by alesnav** [comment]
I don't understand the last string in English version, so I did not add it in this update...

```
<string name="title_activity_click_intent">Click Intent Activity</string>
```

I saw that it is used as `android:label` inside `activity` section of `AndroidManifest.xml`... so it should be used as a description for the app, but I think that it is not described.

Could you update that string in English version?

Thanks!

**Comment by umanx** [comment]
@alesnav This string is used internally within the application (for extension clickActivity). The user never gets to see it, so leaving it untranslated is alright.

**Comment by alesnav** [comment]
Ok, thanks!

**Pull request merged**
